### ISSUE TITLE
When using the non-oss version of ELK stack, only admin can log on

### ISSUE THREAD

**Issue by maglo** [novomatic-tech/keycloak-kibana#23]
If not using the OSS version of the ELK stack, only users with the following (needs all) role mappings can log on:

- manage-dashboards
- view-visualizations
- view-searches
- discover
- manage-kibana
- manage-searches
- manage-visualizations
- view-dashboards

Can be reproduced in dev environment by changing image of Elastic to non-oss in `docker-compose.yml` and removing the `--oss` attribute in the start command. Also need to set `xpack.security.enabled: false` in `kibana.yml`

**Comment by tomnocon** [comment]
Hello @maglo,
I'm currently working on this issue in #24. This plugin has never been tested with X-Pack version of kibana. So, please be patient and wait for new release.

**Comment by tomnocon** [comment]
Fixed in version ```3.0.0```. Please give us feedback if you find any bugs or unexpected behaviours.
