### ISSUE TITLE
Doesn't work with kibana 7.2.0

### ISSUE THREAD

**Issue by argpass** [novomatic-tech/keycloak-kibana#28]
Here is the error log:

> {"type":"log","@timestamp":"2019-08-12T03:22:20Z","tags":["fatal","root"],"pid":1,"message":"{ Error: custom client factory is already set, unable to replace the current one\n    at ScopedSavedObjectsClientProvider.setClientFactory (/usr/share/kibana/src/legacy/server/saved_objects/service/lib/scoped_client_provider.js:30:13)\n    at Object.setScopedSavedObjectsClientFactory (/usr/share/kibana/src/legacy/server/saved_objects/saved_objects_mixin.js:145:63)\n    at setScopedSavedObjectsClientFactory (/usr/share/kibana/plugins/keycloak-kibana/server/services/SecureClusterFacade.js:36:16)\n    at Plugin.init [as externalInit] (/usr/share/kibana/plugins/keycloak-kibana/index.js:209:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  isBoom: true,\n  isServer: true,\n  data: null,\n  output:\n   { statusCode: 500,\n     payload:\n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/generalError' }"}

**Comment by tomnocon** [comment]
We using this plugin with ``Kibana 7.2.0`` and its works fine. Can you provide more info about this error? When does it occur?

**Comment by tomnocon** [comment]
Closed due to inactivity. Feel free to reopen.
