### ISSUE TITLE
Cannot set default strategy more than once

### ISSUE THREAD

**Issue by argpass** [novomatic-tech/keycloak-kibana#29]
It doesn't work with the Kibana 7.2.0. The error "Cannot set default strategy more than once" is raising at the code:

>       server.auth.default('keycloak');

error log:
>  {"type":"log","@timestamp":"2019-08-12T03:33:28Z","tags":["fatal","root"],"pid":1,"message":"{ AssertionError [ERR_ASSERTION]: Cannot set default strategy more than once\n    at new AssertionError (internal/assert.js:269:11)\n    at Object.exports.assert (/usr/share/kibana/node_modules/hoek/lib/index.js:736:11)\n    at module.exports.internals.Auth.default (/usr/share/kibana/node_modules/hapi/lib/auth.js:73:14)\n    at Plugin.init [as externalInit] (/usr/share/kibana/plugins/keycloak-kibana/index.js:202:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  generatedMessage: false,\n  name: 'AssertionError [ERR_ASSERTION]',\n  code: 'ERR_ASSERTION',\n  actual: false,\n  expected: true,\n  operator: '==',\n  isBoom: true,\n  isServer: true,\n  data: null,\n  output:\n   { statusCode: 500,\n     payload:\n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/generalError' }"}
kibana           | 
kibana           |  FATAL  AssertionError [ERR_ASSERTION]: Cannot set default strategy more than once

**Comment by tomnocon** [comment]
You have to disable security plugin from kibana:

```yaml
# disable x-pack security (required)
xpack.security.enabled: false
```

I've added info to readme.
