### ISSUE TITLE
add paremetrs redirect_uri

### ISSUE THREAD

**Issue by artb1sh** [novomatic-tech/keycloak-kibana#30]
Hi 
Add plese redirect_uri config parametr

**Comment by artb1sh** [comment]
![image](https://user-images.githubusercontent.com/4118703/63525296-1e47ac00-c506-11e9-87a1-5ce95d948d0e.png)

**Comment by tomnocon** [comment]
You should configure valid redirect uri in the keycloak configuration - this s not the responsibility of kibana application. 
See: https://github.com/novomatic-tech/keycloak-kibana/blob/3.0.0/env/keycloak/kibana-realm.json#L201

**Comment by artb1sh** [comment]
@tomnocon you hardcoded redirect url in index.js
/sso/login
> const isLoginOrLogout = (request) => {
>   const url = request.raw.req.url;
>   return url.startsWith('/sso/login') || url.startsWith('/sso/logout');
> };
>

**Comment by artb1sh** [comment]
redirect_usl hardoced to adress localhost:5601/sso/login

**Comment by tomnocon** [comment]
@artb1sh uri is not hardcoded in application, only path to login endpoint. I don't see any reason to change that.

**Comment by artb1sh** [comment]
@tomnocon , how used reverse-proxy nginx and kibana stack?

**Comment by tomnocon** [comment]
@artb1sh if you want to configure a custom base path, use `server.basePath` parameter in kibana. See: https://www.elastic.co/guide/en/kibana/7.2/settings.html
