### ISSUE TITLE
SSL error in Kibana version 6.6.1

### ISSUE THREAD

**Issue by ferry1090** [novomatic-tech/keycloak-kibana#38]
Hi All,

Kindly need your advise on this.
Currently I'm using Kibana 6.6.1 so after I install the plugin, I also add in the keycloak config in kibana.yml.

Please find my kibana config below
> #Keycloak Setup
keycloak.serverUrl: https://keycloak/auth
keycloak.realm: keycloak
keycloak.clientId: keycloak-test
keycloak.clientSecret: mks7a4a4-d9se-lke0-97s7-ad7tyn12c16b
keycloak.session.cookieOptions.password: JWFn3Er]PqNZ7n{H$L9aa}Eeg#J`9?zb-/jyt?;#px>?@xaYrx_"P>Y%k[~7VGWV
#Server Setup
server.port: 5601
server.host: "192.168.0.1"
server.ssl.enabled: true
server.ssl.certificate: /app/server.crt
server.ssl.key: /app/server.key
path.data: "/app/kibana/data"
logging.dest: "/app/kibana/kibana.log"
xpack.security.enabled: false
#Elasticsearch Setup
elasticsearch.hosts: ["http://192.168.0.2:9200"]
elasticsearch.requestTimeout: 60000

If I run on htpp keycloak, it is working fine, but when I tried to run as https, it actually give me error.
Do I have to add my keycloak self signed to the truststore? How do I add my self signed keycloak into the Keycloak config?

> { Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
 FATAL  Error: Unable to initialize internal user using client credentials grant. Make sure Service Accounts are enabled for this client and correct values for clientId and clientSecret were provided.

Thank you for your help

**Comment by maglo** [comment]
This `DEPTH_ZERO_SELF_SIGNED_CERT` looks like you are not using a Certification Authority (CA) to issue the certificate used. To use TLS "for real" you should do this. You could use the same CA to issue both the certificate for Kibana and Keycloak.

Then you would have to add the CA certifcate to the Kibana setup. For the process running Kibana, set environment variable `NODE_EXTRA_CA_CERTS` to the path of the CA certificate that issued the certificate for Keycloak.

**Comment by ferry1090** [comment]
I have a valid cert as well, and issue is not happening for the valid environment.
But I am having another problem when i tried to start the kibana again.

>  log   [16:37:01.578] [debug][plugins] Initializing plugin keycloak-kibana@2.0.0
  log   [16:37:01.613] [server][uuid][uuid] Resuming persistent Kibana instance UUID: 6fc76dfb-449b-4612-a3d1-21745e250a0e
  log   [16:37:01.620] [debug][plugin] Checking Elasticsearch version
  log   [16:37:01.632] [info][status][plugin:elasticsearch@6.6.1] Status changed from yellow to green - Ready
  log   [16:37:01.633] [debug][license][xpack] Calling [data] Elasticsearch _xpack API. Polling frequency: 30001
**401:Unauthorized**
  log   [16:37:01.660] [debug][root] shutting root down
  log   [16:37:01.660] [fatal][root] Error: Unable to initialize internal user using client credentials grant. Make sure Service Accounts are enabled for this client and correct values for clientId and clientSecret were provided.
    at InternalGrant.initialize (/usr/share/hover/plugins/keycloak-kibana/server/services/InternalGrant.js:12:19)

Do you have any idea on why i'm getting 401:Unauthorized, is this coming from elasticsearch?
Thank you for your fast response.
